# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
# source 'https://github.com/CocoaPods/Specs.git' # CocoaPods public specs
# source 'https://github.com/Kotlin/kotlin-cocoapods-spec.git' # Kotlin Multiplatform specs

target 'iosApp' do
use_frameworks!
pod 'GoogleSignIn'
end
