package com.sdjic.gradnet.presentation.core

import androidx.compose.ui.unit.dp
import com.sdjic.gradnet.data.network.entity.dto.UserDto

val devanshPic =
    "https://myawsalumnibucket.s3.us-east-1.amazonaws.com/images/ba24cbb0a199416bab7d8d7ae44bc65a.jpg"

val smitPic =
    "https://myawsalumnibucket.s3.us-east-1.amazonaws.com/images/58b73e56d7f24b04af7ab892017ed8ec.jpg"

val aryanPic =
    "https://myawsalumnibucket.s3.us-east-1.amazonaws.com/images/96bfe31507e2423aafce294ba32d02dc.jpg"

val shubhangiPic =
    "https://instagram.fstv5-1.fna.fbcdn.net/v/t51.2885-19/460682937_1175643466880573_8384927044933965467_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_ht=instagram.fstv5-1.fna.fbcdn.net&_nc_cat=105&_nc_oc=Q6cZ2QGNUd_70cqW__ZLHdTxcm93FMfhjw3mGA5CRGD1Fwh8p7bjVRVXw8MKpSJe_niOrRE&_nc_ohc=EZuG3s1hveYQ7kNvgHcvajj&_nc_gid=zohLPsoiTa7EZ68m2DhXMA&edm=AEYEu-QBAAAA&ccb=7-5&oh=00_AYHUdQnbn2Ai18YIgj8JMmcJ97aNndj-Nt1XlUjWRpPtfQ&oe=67E940D4&_nc_sid=ead929"


val LanguagesList = listOf(
    "Hindi",
    "English",
    "Gujarati",
    "Bengali",
    "Telugu",
    "Marathi",
    "Tamil",
    "Kannada",
    "Odia",
    "Punjabi",
    "Malayalam",
    "Mandarin Chinese",
    "Spanish",
    "French",
    "Arabic",
    "Russian",
    "Portuguese",
    "Japanese",
    "German",
    "Korean",
    "Turkish",
    "Vietnamese",
    "Italian",
    "Polish",
    "Ukrainian",
    "Dutch",
    "Thai",
    "Persian",
    "Swahili",
    "Tagalog"
)

val SkillList = listOf(
    "Kotlin",
    "Swift",
    "C",
    "C++",
    "C#",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "PHP",
    "Ruby",
    "R",
    "Go",
    "Rust",
    "Perl",
    "Scala",
    "Shell Scripting",
    "Dart",
    "MATLAB",
    "VB.NET",
    "Objective-C",
    "HTML5",
    "CSS3",
    "SASS/SCSS",
    "Bootstrap",
    "Tailwind CSS",
    "Android",
    "IOS",
    "Android Compose",
    "Compose Multiplatform",
    "Kotlin Multiplatform",
    "React.js",
    "Vue.js",
    "Angular",
    "Node.js",
    "Next.js",
    "Nuxt.js",
    "Spring Boot",
    "Hibernate",
    "Django",
    "Flask",
    "Ruby on Rails",
    "ASP.NET",
    "Laravel",
    "Symfony",
    "Express.js",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "OpenCV",
    "Hadoop",
    "Spark",
    "Tableau",
    "Power BI",
    "Jira",
    "Trello",
    "Communication",
    "Teamwork",
    "Leadership",
    "Problem-Solving",
    "Time Management",
    "Critical Thinking",
    "Adaptability",
    "Creativity",
    "Interpersonal Skills",
    "Public Speaking",
    "Negotiation",
    "Project Management",
    "Technical Skills",
    "Analytical Skills",
    "Customer Service",
    "Data Analysis",
    "Networking",
    "Decision Making",
    "Writing Skills",
    "Conflict Resolution",
    "Emotional Intelligence",
    "Research Skills",
    "Presentation Skills",
    "Attention to Detail",
    "Sales Skills",
    "Organizational Skills",
    "Programming",
    "Marketing",
    "SEO/SEM",
    "Graphic Design",
    "UX/UI Design",
    "Social Media Management",
    "Copywriting",
    "Editing",
    "IT Support",
    "Web Development",
    "Mobile Development",
    "Cloud Computing",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Cybersecurity",
    "Blockchain",
    "Product Management",
    "Supply Chain Management",
    "Accounting",
    "Financial Analysis",
    "Budgeting",
    "Auditing",
    "Tax Preparation",
    "Human Resources Management",
    "Recruitment",
    "Training and Development",
    "Change Management",
    "Compliance",
    "Event Planning",
    "Operations Management",
    "Quality Assurance",
    "Lean Manufacturing",
    "Agile Methodology",
    "Scrum Mastery",
    "Risk Management",
    "Business Analysis",
    "Strategic Planning",
    "Content Creation",
    "Digital Marketing",
    "E-commerce",
    "Video Production",
    "Photography",
    "Customer Relationship Management (CRM)",
    "SQL",
    "DevOps",
    "Systems Analysis",
    "Ethical Hacking",
    "Mobile Testing",
    "Technical Writing",
    "Legal Research",
    "Contract Management",
    "Supply Chain Optimization",
    "Cross-cultural Competence",
    "Bilingualism/Multilingualism",
    "Teaching",
    "Coaching",
    "Mentoring",
    "Fundraising",
    "Volunteer Management",
    "Crisis Management",
    "Public Relations",
    "Media Relations",
    "Policy Development",
    "Urban Planning",
    "Architecture",
    "Construction Management",
    "Engineering Design",
    "Healthcare Management",
    "Clinical Research",
    "Nursing Skills",
    "Patient Care",
    "Pharmacy Knowledge",
    "Environmental Science",
    "Renewable Energy Knowledge",
    "Logistics",
    "Inventory Management",
    "Fleet Management"
)

val DummyBgImage =
    "https://images.wallpaperscraft.com/image/single/starry_sky_milky_way_stars_118495_1600x900.jpg"
val DummyDpImage =
    "https://images.unsplash.com/photo-1639149888905-fb39731f2e6c?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
val LOREM =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

val TOP_BAR_HEIGHT = 56.dp